### ISSUE TITLE
A short README for utils (CSS var utility functions)

### ISSUE THREAD

**Issue by apatrida** [astahmer/pandabox#34]
I think I know what this does:
packages/utils

But I can't be sure I know what that does.

Can we get a short README describing the functions there?

**Comment by astahmer** [comment]
assignInlineVars is like https://vanilla-extract.style/documentation/packages/dynamic/#assigninlinevars but type-safe with typings using your panda.config tokens
https://github.com/astahmer/pandabox/blob/main/packages/utils/__tests__/assign-inline-vars.test.ts

`cssVar` allows creating creating css vars as JS objects so you can reference them in your panda config or at runtime

`wrapValue` will wrap every objects inside the first argument with a `{ value: xxx }`, mostly meant to easily migrate from a chakra theme tokens object to a panda.config tokens object

**Comment by apatrida** [comment]
thanks!
