### ISSUE TITLE
Make it clear if unplugin-panda-macro works in dev mode

### ISSUE THREAD

**Issue by apatrida** [astahmer/pandabox#35]
The docs for the unplugin-pand-macro talk about "build time" and not needing the Panda CLI nor PostCSS:
 
https://github.com/astahmer/pandabox/tree/main/packages/unplugin-panda-macro

Does that cover dev mode as well?  Make this clear in the README.

**Comment by astahmer** [comment]
yes it works in dev as well
it will inline the results of Panda functions/JSX components as string at build-time, e.g before running in your browser

**Comment by apatrida** [comment]
great!
