### ISSUE TITLE
Macro converts unrelated components

### ISSUE THREAD

**Issue by nucleartux** [astahmer/pandabox#40]
I made a small reproduction here: https://github.com/astahmer/pandabox/compare/main...nucleartux:pandabox:repro?expand=1
<img width="654" alt="image" src="https://github.com/astahmer/pandabox/assets/199706/f29dba05-914b-4a92-81e8-1c7bfac06e71">
From the code, you can see that I don't import `Stack` from anywhere. However, for some reason, the Panda macro converts `Stack` to its own component (first div in the screenshot). If I rename `Stack` to `Stack2`, everything works as expected (second div in the screenshot).
Is this the expected behavior? I have many components in my project with conflicting names (like `Stack`, `Container`, `Circle`), which should not be changed in any way by Panda.

**Comment by astahmer** [comment]
you're right, this is not the expected behaviour
I'll look into that !
