### ISSUE TITLE
@pandabox/prettier-plugin: `all: unset` sorting

### ISSUE THREAD

**Issue by Faithfinder** [astahmer/pandabox#61]
`all: unset` gets sorted below a bunch of stuff (I'm guessing falls into "Other" category?). IMO this should always be at the top of the list. I think that should be the default behaviour, though I'm willing to set it up, just couldn't understand how - maybe an example is in order?

**Comment by astahmer** [comment]
hey, the sorting is based on your panda config `utilities`, they each have a `group` which is only useful for the prettier plugin. you can extend your utilities to add/update a given group. [see the docs](https://github.com/astahmer/pandabox/blob/e4042532903a8f604de472a75a3555507c3915d1/packages/prettier-plugin/README.md#extending)

so you could either do something like this in your `panda.config.ts`:
```ts
import { defineConfig } from "@pandacss/dev";

export const config = defineConfig({
  // ...
  utilities: {
    extend: {
      all: {
        group: "System"
      }
    }
  },
});
```

[`System` being the 1st group in the order](https://github.com/astahmer/pandakit/blob/30e511c58b8b23fe79ee2563f931e8511dcfe414/packages/prettier-plugin/src/get-priority-index.ts#L9)

or you could use the `pandaFirstProps: ["all"]` [option of the prettier plugin](https://github.com/astahmer/pandabox/blob/e4042532903a8f604de472a75a3555507c3915d1/packages/prettier-plugin/README.md#pandafirstprops) to force it without touching your panda.config
